# Generated by Django 4.2.5 on 2023-10-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='is_published',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('phone', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.goods')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Shop.category'),
        ),
    ]
