# Generated by Django 4.2.5 on 2023-10-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_category_goods_is_published_order_goods_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
