# Generated by Django 4.2.5 on 2023-11-17 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0003_goods_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='good',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.goods'),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Shop.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
