# Generated by Django 4.2.5 on 2023-11-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_remove_order_good_remove_order_quantity_order_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basket',
        ),
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.ManyToManyField(to='Shop.basket'),
        ),
    ]
